// ── Configuration ─────────────────────────────────────────────────────────────
const MAX_CHARS = 1000;

// ── Demo scenarios: keyword → {steps, tool_call?, answer} ─────────────────────
const DEMO_SCENARIOS = [
  {
    keywords: ["create", "repo", "repositor"],
    steps: [
      { icon: "🔍", text: "Parsing request: identify target org and repo name…" },
      { icon: "🧠", text: "Reasoning: need create_repo tool — constructing parameters…" },
      { icon: "⚙️", text: "Calling tool: create_repo", type: "tool" },
      { icon: "✅", text: "Repository created and seed files injected." },
      { icon: "📝", text: "Composing final response…" },
    ],
    toolCall: (msg) => ({
      name: "create_repo",
      parameters: {
        name: extractRepoName(msg) || "my-infinity-site",
        description: "AI-generated repo for the Pewpi-Infinity ecosystem",
        private: false,
        auto_init: true,
        license: "mit",
        topics: ["ai", "gemma3", "infinity"],
        files: [
          { path: "index.html", content: "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Infinity</title></head><body><h1>∞ Infinity</h1></body></html>" },
          { path: "README.md", content: "# Infinity Site\nAI-generated by Gemma 3.\n" },
        ],
      },
    }),
    answer: (msg) =>
      `✅ Done! I created the repository **${extractRepoName(msg) || "my-infinity-site"}** under the \`www-infinity\` org.\n\nThe repo was initialised with an \`index.html\` and \`README.md\`, tagged with topics \`ai, gemma3, infinity\`, and licensed under MIT.\n\nRun the following to enable GitHub Pages:\n\`\`\`\npython gemma_agent.py --prompt "Deploy www-infinity/${extractRepoName(msg) || "my-infinity-site"}"\n\`\`\``,
  },
  {
    keywords: ["deploy", "pages", "publish", "site"],
    steps: [
      { icon: "🔍", text: "Identifying target repository and branch…" },
      { icon: "🧠", text: "Reasoning: need deploy_site tool — enabling GitHub Pages…" },
      { icon: "⚙️", text: "Calling tool: deploy_site", type: "tool" },
      { icon: "✅", text: "GitHub Pages deployment triggered." },
      { icon: "📝", text: "Generating deployment summary…" },
    ],
    toolCall: (msg) => ({
      name: "deploy_site",
      parameters: {
        repo: "www-infinity/pewpi-landing",
        source_branch: "main",
        source_path: "/",
      },
    }),
    answer: () =>
      `🚀 Deployment initiated! GitHub Pages is now enabled for \`www-infinity/pewpi-landing\`.\n\nYour site will be live at:\n**https://www-infinity.github.io/pewpi-landing/**\n\nDNS propagation typically takes 1–2 minutes.`,
  },
  {
    keywords: ["analys", "analyze", "check", "review", "bug", "error"],
    steps: [
      { icon: "🔍", text: "Identifying repository to analyse…" },
      { icon: "🧠", text: "Reasoning: fetching repo tree + sampling key files…" },
      { icon: "⚙️", text: "Calling tool: analyze_code", type: "tool" },
      { icon: "🔬", text: "Processing code samples with Gemma 3 reasoning…" },
      { icon: "✅", text: "Analysis complete — compiling findings." },
    ],
    toolCall: () => ({
      name: "analyze_code",
      parameters: {
        repo: "www-infinity/Npx-Claude-flow-",
        focus: "bugs",
        paths: ["claude_worker.py", "gemma_agent.py"],
      },
    }),
    answer: () =>
      `🔎 Analysis of \`www-infinity/Npx-Claude-flow-\`:\n\n**claude_worker.py**\n• No critical bugs found. API key is correctly read from env.\n• Minor: missing retry logic for transient HTTP 429 errors.\n\n**gemma_agent.py**\n• Well-structured. Tool registry pattern is solid.\n• Suggestion: add exponential back-off around \`urlopen\` calls.\n\nOverall health: 🟢 Good`,
  },
  {
    keywords: ["browse", "fetch", "read", "scrape", "url", "http", "website"],
    steps: [
      { icon: "🔍", text: "Parsing URL from request…" },
      { icon: "🧠", text: "Reasoning: need browse_url tool to fetch page content…" },
      { icon: "⚙️", text: "Calling tool: browse_url", type: "tool" },
      { icon: "📄", text: "Extracting main content from HTML…" },
      { icon: "✅", text: "Content retrieved — summarising…" },
    ],
    toolCall: (msg) => {
      const url = extractUrl(msg) || "https://github.com/www-infinity/Npx-Claude-flow-";
      return {
        name: "browse_url",
        parameters: { url, extract: "main_content", max_length: 4096 },
      };
    },
    answer: (msg) => {
      const url = extractUrl(msg) || "https://github.com/www-infinity/Npx-Claude-flow-";
      return `📄 Retrieved **${url}**\n\nThis is the **Npx-Claude-flow-** repository — an AI-powered multi-agent workflow platform. It contains:\n• \`claude_worker.py\` — bulk repo analyser using the Anthropic API\n• \`gemma_agent.py\` — Gemma 3 autonomous agent with function calling\n• \`website/\` — Static marketing site with chat UI\n• \`schemas/gemma_tools.json\` — Tool call schemas for GitHub operations`;
    },
  },
  {
    keywords: ["inject", "file", "add file", "upload", "write"],
    steps: [
      { icon: "🔍", text: "Parsing target repo, path, and content…" },
      { icon: "🧠", text: "Reasoning: need inject_file tool — encoding content as Base64…" },
      { icon: "⚙️", text: "Calling tool: inject_file", type: "tool" },
      { icon: "✅", text: "File committed to repository." },
      { icon: "📝", text: "Composing confirmation…" },
    ],
    toolCall: (msg) => ({
      name: "inject_file",
      parameters: {
        repo: "www-infinity/pewpi-landing",
        path: "src/app.js",
        content: "// Pewpi Infinity — AI-powered\nconsole.log('Agent online');\n",
        message: "feat: add app entry point via Gemma agent",
        branch: "main",
      },
    }),
    answer: () =>
      `✅ File **src/app.js** committed to \`www-infinity/pewpi-landing\` on branch \`main\`.\n\nCommit message: _"feat: add app entry point via Gemma agent"_`,
  },
  {
    keywords: ["build", "website", "landing", "page", "scaffold", "generate"],
    steps: [
      { icon: "🔍", text: "Understanding site requirements from request…" },
      { icon: "🧠", text: "Reasoning: plan multi-step — create repo → inject files → deploy…" },
      { icon: "⚙️", text: "Calling tool: create_repo", type: "tool" },
      { icon: "⚙️", text: "Calling tool: inject_file (index.html)", type: "tool" },
      { icon: "⚙️", text: "Calling tool: inject_file (styles.css)", type: "tool" },
      { icon: "⚙️", text: "Calling tool: deploy_site", type: "tool" },
      { icon: "✅", text: "Full pipeline complete — site live." },
    ],
    toolCall: () => ({
      name: "create_repo",
      parameters: {
        name: "infinity-generated-site",
        description: "Full-stack site scaffolded by Gemma 3 agent pipeline",
        private: false,
        auto_init: true,
        license: "mit",
        topics: ["ai", "generated", "infinity", "gemma3"],
        files: [
          {
            path: "index.html",
            content: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>AI Site</title>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>∞ Infinity Site</h1>\n  <p>Generated by Gemma 3.</p>\n</body>\n</html>",
          },
          { path: "styles.css", content: "body { font-family: sans-serif; max-width: 40rem; margin: 4rem auto; }\nh1   { color: #7c6af5; }\n" },
          { path: "README.md", content: "# Infinity Generated Site\nScaffolded by the Gemma 3 autonomous agent.\n" },
        ],
      },
    }),
    answer: () =>
      `🎉 Full pipeline complete!\n\n1. **Repo created**: \`www-infinity/infinity-generated-site\`\n2. **Files injected**: \`index.html\`, \`styles.css\`, \`README.md\`\n3. **GitHub Pages enabled**: https://www-infinity.github.io/infinity-generated-site/\n\nThe entire workflow — reasoning, tool calls, and deployment — ran in under 10 seconds.`,
  },
];

const DEFAULT_STEPS = [
  { icon: "🔍", text: "Parsing the request…" },
  { icon: "🧠", text: "Reasoning through possible approaches…" },
  { icon: "💡", text: "Selecting the best response strategy…" },
  { icon: "📝", text: "Composing answer…" },
];

const DEFAULT_ANSWER = (msg) =>
  `I'm the Gemma 3 agent for the Infinity ecosystem. I can help you:\n\n• **Create GitHub repositories** — _"Create a repo called my-site"_\n• **Inject files** — _"Add a README to www-infinity/my-site"_\n• **Deploy sites** — _"Deploy www-infinity/my-site to GitHub Pages"_\n• **Analyse code** — _"Check www-infinity/Npx-Claude-flow- for bugs"_\n• **Browse URLs** — _"Fetch https://github.com/…"_\n• **Build full sites** — _"Build a landing page for Pewpi"_\n\nTry one of the suggestion chips below, or type your own request.`;

// ── Helpers ───────────────────────────────────────────────────────────────────
// Extract a repo name from natural-language text using a single ordered pattern list.
const REPO_NAME_PATTERNS = [
  /(?:call(?:ed)?|name(?:d)?(?:\s+it)?)\s+["']?([\w-]+)["']?/i,
  /repo\s+["']?([\w-]+)["']?/i,
  /["']([\w-]+)["']/,
];

function extractRepoName(text) {
  for (const pattern of REPO_NAME_PATTERNS) {
    const m = text.match(pattern);
    if (m) return m[1];
  }
  return null;
}

function extractUrl(text) {
  const m = text.match(/https?:\/\/[^\s]+/);
  return m ? m[0] : null;
}

function matchScenario(text) {
  const lower = text.toLowerCase();
  return DEMO_SCENARIOS.find((s) => s.keywords.some((k) => lower.includes(k))) || null;
}

// ── JSON syntax highlighter ───────────────────────────────────────────────────
function highlightJson(obj) {
  const str = JSON.stringify(obj, null, 2);
  return str
    .replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?)/g,
      (match) => {
        if (/^"/.test(match)) {
          if (/:$/.test(match)) return `<span class="json-key">${match}</span>`;
          return `<span class="json-str">${match}</span>`;
        }
        if (/true|false/.test(match)) return `<span class="json-bool">${match}</span>`;
        if (/null/.test(match))       return `<span class="json-null">${match}</span>`;
        return `<span class="json-num">${match}</span>`;
      });
}

// ── DOM helpers ───────────────────────────────────────────────────────────────
function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToHtml(text) {
  return escapeHtml(text)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/_(.+?)_/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, `<code style="font-family:var(--font-mono);font-size:.85em;color:var(--color-accent)">$1</code>`)
    .replace(/```[\s\S]*?```/g, (m) => {
      const code = m.replace(/^```\w*\n?/, "").replace(/```$/, "");
      return `<pre style="margin:.5rem 0;background:var(--color-bg);padding:.6rem .8rem;border-radius:.4rem;overflow-x:auto;font-family:var(--font-mono);font-size:.8rem;color:var(--color-accent)">${escapeHtml(code)}</pre>`;
    })
    .replace(/\n/g, "<br>");
}

// ── Reasoning panel ───────────────────────────────────────────────────────────
const reasoningBody = document.getElementById("reasoning-body");
const reasoningDot  = document.getElementById("reasoning-dot");
const reasoningEmpty = document.getElementById("reasoning-empty");

function clearReasoning() {
  reasoningBody.innerHTML = "";
  if (reasoningEmpty) reasoningBody.appendChild(reasoningEmpty);
  reasoningDot.classList.remove("active");
}

function addReasoningStep(step, delay = 0) {
  return new Promise((resolve) => {
    setTimeout(() => {
      if (reasoningEmpty && reasoningEmpty.parentNode === reasoningBody) {
        reasoningBody.removeChild(reasoningEmpty);
      }
      const el = document.createElement("div");
      el.className = `r-step r-step--active${step.type === "tool" ? " r-step--tool" : ""}`;
      el.innerHTML = `<span class="r-step__icon">${step.icon}</span><span class="r-step__text">${escapeHtml(step.text)}</span>`;
      reasoningBody.appendChild(el);
      reasoningBody.scrollTop = reasoningBody.scrollHeight;
      resolve();
    }, delay);
  });
}

// ── Message list ──────────────────────────────────────────────────────────────
const messagesList = document.getElementById("messages");
let isProcessing = false;

const VALID_ROLES = new Set(["user", "assistant", "system"]);

function appendMessage({ role, html, toolCall }) {
  const safeRole = VALID_ROLES.has(role) ? role : "system";
  const wrap = document.createElement("div");
  wrap.className = `message message--${safeRole}`;

  const avatar = document.createElement("div");
  avatar.className = "message__avatar";
  avatar.textContent = safeRole === "user" ? "U" : safeRole === "assistant" ? "G" : "ℹ";

  const bubble = document.createElement("div");
  bubble.className = "message__bubble";
  bubble.innerHTML = html;

  // Append tool call block if present
  if (toolCall) {
    const block = document.createElement("div");
    block.className = "tool-call-block";
    block.innerHTML = `
      <div class="tool-call-block__header">
        <span class="tool-call-block__label">⚙ tool_call: ${escapeHtml(toolCall.name)}</span>
        <i class="tool-call-block__chevron">▶</i>
      </div>
      <div class="tool-call-block__body">
        <pre>${highlightJson(toolCall)}</pre>
      </div>`;
    block.querySelector(".tool-call-block__header").addEventListener("click", () => {
      block.classList.toggle("is-open");
    });
    bubble.appendChild(block);
  }

  if (safeRole === "user") {
    wrap.appendChild(bubble);
    wrap.appendChild(avatar);
  } else {
    wrap.appendChild(avatar);
    wrap.appendChild(bubble);
  }

  messagesList.appendChild(wrap);
  messagesList.scrollTop = messagesList.scrollHeight;
  return wrap;
}

function appendTypingIndicator() {
  const wrap = document.createElement("div");
  wrap.className = "message message--assistant";
  wrap.id = "typing-indicator";
  wrap.innerHTML = `
    <div class="message__avatar">G</div>
    <div class="message__bubble">
      <div class="typing-indicator"><span></span><span></span><span></span></div>
    </div>`;
  messagesList.appendChild(wrap);
  messagesList.scrollTop = messagesList.scrollHeight;
  return wrap;
}

function removeTypingIndicator() {
  const el = document.getElementById("typing-indicator");
  if (el) el.remove();
}

// ── Core send logic ───────────────────────────────────────────────────────────
const sendBtn  = document.getElementById("send-btn");
const textarea = document.getElementById("chat-input");
const charEl   = document.getElementById("char-count");

async function sendMessage(text) {
  if (!text.trim() || isProcessing) return;
  isProcessing = true;
  sendBtn.disabled = true;

  // User message
  appendMessage({ role: "user", html: markdownToHtml(text) });
  textarea.value = "";
  textarea.style.height = "auto";
  if (charEl) charEl.textContent = `0 / ${MAX_CHARS}`;

  clearReasoning();
  reasoningDot.classList.add("active");
  const typingEl = appendTypingIndicator();

  // Match demo scenario
  const scenario = matchScenario(text);
  const steps   = scenario ? scenario.steps : DEFAULT_STEPS;
  const answer  = scenario ? scenario.answer(text) : DEFAULT_ANSWER(text);
  const tc      = scenario?.toolCall ? scenario.toolCall(text) : null;

  // Animate reasoning steps
  const BASE_DELAY = 600;
  const promises = steps.map((step, i) => addReasoningStep(step, i * BASE_DELAY));
  await Promise.all(promises);

  // Small pause before final response
  await new Promise((r) => setTimeout(r, 400));

  reasoningDot.classList.remove("active");
  removeTypingIndicator();

  // Mark last step done
  reasoningBody.querySelectorAll(".r-step--active").forEach((el) => {
    el.classList.remove("r-step--active");
    el.classList.add("r-step--done");
  });

  appendMessage({
    role: "assistant",
    html: markdownToHtml(answer),
    toolCall: tc || null,
  });

  isProcessing = false;
  sendBtn.disabled = false;
  textarea.focus();
}

// ── Input handlers ────────────────────────────────────────────────────────────
sendBtn.addEventListener("click", () => sendMessage(textarea.value.trim()));

textarea.addEventListener("keydown", (e) => {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    sendMessage(textarea.value.trim());
  }
});

textarea.addEventListener("input", () => {
  // Auto-resize
  textarea.style.height = "auto";
  textarea.style.height = `${Math.min(textarea.scrollHeight, 128)}px`;
  // Char count
  if (charEl) {
    const len = textarea.value.length;
    charEl.textContent = `${len} / ${MAX_CHARS}`;
    charEl.style.color = len > MAX_CHARS * 0.9 ? "var(--color-accent)" : "";
  }
});

// ── Suggestion chips ──────────────────────────────────────────────────────────
document.querySelectorAll(".suggestion-chip").forEach((chip) => {
  chip.addEventListener("click", () => {
    if (!isProcessing) sendMessage(chip.dataset.prompt);
  });
});

// ── Mobile reasoning panel toggle ─────────────────────────────────────────────
const mobileToggle = document.getElementById("mobile-reasoning-toggle");
const reasoningPanel = document.getElementById("reasoning-panel");

if (mobileToggle && reasoningPanel) {
  mobileToggle.addEventListener("click", () => {
    reasoningPanel.classList.toggle("is-visible");
    mobileToggle.setAttribute(
      "aria-expanded",
      String(reasoningPanel.classList.contains("is-visible"))
    );
  });
}
